### PR TITLE
Block weights do not seem to work

### PR DESCRIPTION
**Pull request by njt1982**
Blocks seem to be output based on the order they are in a single context.

So if I have two contexts, I just get the blocks appended to the list rather than sorted by weight.

### CODE REVIEW

**Comment by njt1982** [comment]
This fixed the issue for me...

**Comment by NormySan** [comment]
Thanks for the pull-requests @njt1982. I've moved the code to another repository to be able to merge it into the code at Drupal.org and forgot to close this one down.

If you don't mind it would be great if you could implement the same pull requests over at the new repo https://github.com/oddhill/context

Thanks!

**Comment by njt1982** [comment]
Will do

**Comment by njt1982** [comment]
See https://github.com/oddhill/context/pull/7

**Pull request closed without merging**
